services:
  mongodb:
    container_name: catalog-mongodb
    image: mongo:6
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  api:
    container_name: catalog-api
    image: node:18
    working_dir: /usr/src/app
    restart: always # Policy applied to the container termination
    environment: # Environment variables
      - MONGO_URL=mongodb://mongodb:27017/catalog
      - PORT=3000
    volumes: # Defines the volume to be mounted in the container
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./dist:/usr/src/app/dist/
    ports:  # Exposes ports to the host (HOST: CONTAINER)
      - 3000:3000
    command: bash -c "npm install && npm run dev"  #Overrides the efault command of the image
    links: # Links the container to another container
      - mongodb
    depends_on: # defines the dependency of the container
      - mongodb